import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "keshav",
      email: "keshav@gmail.com",
      password: bcrypt.hashSync("1111", 8),
      isAdmin: true,
    },
    {
      name: "user",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1111", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "A1_nepal",
      category: "one_piece",
      image: "/images/product-7.jpg",
      price: 700,
      countInstock: 10,
      brand: "A1",
      rating: 4.5,
      numReviews: 12,
      description: "high quality products",
    },
    {
      name: "A2_nepal",
      category: "pants",
      image: "/images/product-1.jpg",
      price: 800,
      countInstock: 20,
      brand: "A2",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "A3_nepal",
      category: "inner",
      image: "/images/product-3.jpg",
      price: 750,
      countInstock: 15,
      brand: "A4",
      rating: 5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "A4_nepal",
      category: "shirts",
      image: "/images/product-4.jpg",
      price: 600,
      countInstock: 0,
      brand: "A4",
      rating: 4,
      numReviews: 6,
      description: "high quality products",
    },
    {
      name: "A5_nepal",
      category: "underwear",
      image: "/images/product-5.jpg",
      price: 780,
      countInstock: 65,
      brand: "A5",
      rating: 3.5,
      numReviews: 10,
      description: "high quality products",
    },
    {
      name: "A6_nepal",
      category: "inner",
      image: "/images/product-6.jpg",
      price: 850,
      countInstock: 12,
      brand: "A6",
      rating: 5,
      numReviews: 11,
      description: "high quality products",
    },
  ],
};
export default data;
